### ISSUE TITLE
Release 0.1.1

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli_websocket#4]

**Comment by tgrk** [comment]
Hey, any plans on releasing latest changes on master? Due to changes in `crypto` module, it is not possible to use this great middleware on the latest OTP versions. In case you need a hand with some coding/testing part I am more than happy to help.

Cheers

**Comment by yurrriq** [comment]
Thanks for the heads up. My coding time is limited, but I'd be happy to review a PR.

**Comment by yurrriq** [comment]
:tada: https://hex.pm/packages/elli_websocket/0.1.1

Thanks, everyone!
